version: '3.7'
services:
  netflix:
    image: netflixclone:latest
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - TMDB_V3_API_KEY=dd049199416fb29c502b0077769dd151
        - NO_CACHE=true
    ports:
      - "80:80"
    environment:
      - PORT=80
    restart: "no"