name: SonarQube Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Node.js (for TypeScript projects)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the desired Node.js version

      # Install Java 17 (SonarQube requires at least Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Java distribution

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Install SonarQube Scanner
      - name: Install SonarQube Scanner
        run: |
          npm install -g sonar-scanner

      # Run TypeScript SonarQube scan
      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Netflix_Clone \
            -Dsonar.sources=./ \
            -Dsonar.language=ts \
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.host.url=http://13.70.185.192:9000 \
            -Dsonar.login=$SONARQUBE_TOKEN
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
