name: SonarQube Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install SonarQube Scanner
      - name: Install SonarQube Scanner
        run: |
          sudo apt-get install openjdk-11-jre
          sudo apt-get install sonar-scanner

      # Run SonarQube scan
      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.sources=./ \
            -Dsonar.host.url=http://52.147.51.124:9000 \
            -Dsonar.login=$SONARQUBE_TOKEN
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
